ministryofjustice/ndelius-new-tech

- app/assets/javascripts/nationalsearch/actions/search.js
- app/assets/javascripts/nationalsearch/components/offenderSearchPage.js
- app/assets/javascripts/nationalsearch/containers/offenderSearchPageContainer.js
- app/controllers/NationalSearchController.java
- app/views/nationalSearch.scala.html
- conf/application.conf
- package.json
- test/assets/javascripts/nationalsearch/components/offenderSearchPageTest.js
https://trello.com/c/5JPEN1t2/202-search-tech-spike-previous-search-term-when-navigating-away-from-search
> 202 remember search

- app/assets/javascripts/nationalsearch/components/offenderSearch.js
- app/assets/javascripts/nationalsearch/components/offenderSearchPage.js
- app/assets/javascripts/nationalsearch/components/searchFooter.js
- app/assets/javascripts/nationalsearch/components/suggestions.js
- app/assets/stylesheets/project/_components.scss
- app/assets/stylesheets/project/_forms.scss
After speaking with Bill and Greg - we've decided to move "addresses" to the end of the placeholder text so the following is correct:
"Any combination of names + dates of birth + ID numbers + addresses"
And we then moved the address bullet point to the bottom for consistency.
After this; I went through it with Bill and we corrected the sizes, layout and spacing based on his original designs.
> 342 search content

- app/assets/javascripts/nationalsearch/components/offenderSearch.js
- app/assets/javascripts/nationalsearch/components/searchFooter.js
Updated copy as per discussion with Greg and Nick Gallon.
> Copy changes as per discussion

- app/assets/stylesheets/national-search.scss
I have corrected the layout issues when the search page is viewed on narrow devices/resolutions.
> Fixed search layout issues

- app/views/paroleParom1Report/page3.scala.html
- app/views/paroleParom1Report/page4.scala.html
- app/views/paroleParom1Report/page5.scala.html
- app/views/paroleParom1Report/page6.scala.html
Updated guidance on Victims UI
Updated guidance on RoSH at point of sentence UI
Updated guidance on OPD pathway UI
> Updated guidance on Prisoner contact UI

- app/data/ParoleParom1ReportData.java
- app/views/helper/govukInfoErrors.scala.html
- app/views/paroleParom1Report/hiddenInputs/page16Fields.scala.html
- app/views/paroleParom1Report/page15.scala.html
- app/views/paroleParom1Report/page16.scala.html
- app/views/paroleParom1Report/page17.scala.html
- app/views/paroleParom1Report/page18.scala.html
- features/bdd/paroleparom1report/riskManagementPlan.feature
- test/bdd/paroleparom1report/RiskManagementPlanSteps.java
This also has supporting PDF and Smoke Test branches
> 164 parole guidance 3

- app/views/paroleParom1Report/page11.scala.html
- features/bdd/paroleparom1report/currentRiskAssessmentScore.feature
- test/bdd/paroleparom1report/CurrentRiskAssessmentScoresSteps.java
- test/bdd/paroleparom1report/GlobalSteps.java
- test/views/pages/paroleparom1report/ParoleParom1PopupReportPage.java
> Changed field labels

- app/assets/javascripts/nationalsearch/components/filter.js
- app/assets/javascripts/nationalsearch/components/offenderSearchPage.js
- app/assets/javascripts/nationalsearch/components/offenderSearchSummary.js
- app/assets/javascripts/nationalsearch/components/searchTypeSelector.js
- app/assets/javascripts/offendersummary/components/offenderDetails.js
- app/assets/javascripts/offendersummary/components/offenderIdentity.js
- app/views/nationalSearch.scala.html
- app/views/offenderSummary.scala.html
- test/assets/javascripts/nationalsearch/components/offenderSearchSummaryTest.js
- test/controllers/OffenderSummaryControllerTest.java
As part of testing accessibility in Dragon and JAWS I spotted some errors and redundant bits in the HTML so have fixed them.
> Techtask html fixes

- app/assets/javascripts/application.js
Corrected label in tracking data
> Updated analytics code to capture SFR and PAROM1

- Elasticsearch.postman_collection.json
- README.md
- docker-compose.yml
Included docker-compose for Elasticsearch and MongoDB
Included Postman collection to populate Elasticsearch
Updated README with better/clear instructions for building and runnning locally.
> Simplify and document development

- Jenkinsfile
- app/controllers/OralReportController.java
- app/data/OralReportData.java
- app/views/helper/main_oralReport.scala.html
- app/views/oralReport/cancelled.scala.html
- app/views/oralReport/completed.scala.html
- app/views/oralReport/fragment/checkReportEntry.scala.html
- app/views/oralReport/fragment/footer.scala.html
- app/views/oralReport/fragment/popup.scala.html
- app/views/oralReport/hiddenInputs/commonFields.scala.html
- app/views/oralReport/hiddenInputs/page2Fields.scala.html
- app/views/oralReport/menu/navigation.scala.html
- app/views/oralReport/menu/navigationEntries.scala.html
- app/views/oralReport/menu/navigationEntry.scala.html
- app/views/oralReport/page1.scala.html
- app/views/oralReport/page2.scala.html
- app/views/oralReport/page3.scala.html
- conf/routes
Initial copy of SFR for converting into the Oral version
> PIC-789 Oral report setup

- app/data/OralReportData.java
- app/views/oralReport/cancelled.scala.html
- app/views/oralReport/completed.scala.html
- app/views/oralReport/fragment/popup.scala.html
- app/views/oralReport/hiddenInputs/page11Fields.scala.html
- app/views/oralReport/hiddenInputs/page3Fields.scala.html
- app/views/oralReport/hiddenInputs/page4Fields.scala.html
- app/views/oralReport/hiddenInputs/page5Fields.scala.html
- app/views/oralReport/hiddenInputs/page6Fields.scala.html
- app/views/oralReport/hiddenInputs/page7Fields.scala.html
- app/views/oralReport/hiddenInputs/page8Fields.scala.html
- app/views/oralReport/hiddenInputs/page9Fields.scala.html
- app/views/oralReport/menu/navigationEntries.scala.html
- app/views/oralReport/page1.scala.html
- app/views/oralReport/page10.scala.html
- app/views/oralReport/page11.scala.html
- app/views/oralReport/page3.scala.html
- app/views/oralReport/page4.scala.html
- app/views/oralReport/page5.scala.html
- app/views/oralReport/page6.scala.html
- app/views/oralReport/page7.scala.html
- app/views/oralReport/page8.scala.html
- app/views/oralReport/page9.scala.html
Updated report to include all sections and changes compared to PSR
> Pic 789 oral report setup

- app/views/helper/main_oralReport.scala.html
- app/views/oralReport/cancelled.scala.html
- app/views/oralReport/completed.scala.html
- app/views/oralReport/page10.scala.html
Updated content.
Corrected title on all pages.
Removed feedback links throughout report.
Includes work on PIC-791 and PIC-792
> PIC-790, PIC-791 and PIC-792

- app/views/oralReport/page8.scala.html
Updated layout
Updated hint text
> PIC-812 Proposal

- app/views/oralReport/page5.scala.html
- app/views/oralReport/page8.scala.html
Added new hint text content
Updated content on page
> Pic 814 offence analysis

- app/data/OralReportData.java
- app/views/oralReport/hiddenInputs/page6Fields.scala.html
- app/views/oralReport/page6.scala.html
…issue
- Added 'What to include' summary with hint text
- Added details text area for each issue
- Removed radio buttons and associated guidance text
- Removed evidence section
> Pic 815 offender assessment

- app/views/oralReport/page2.scala.html
- app/views/oralReport/page3.scala.html
- app/views/oralReport/page4.scala.html
- app/views/oralReport/page6.scala.html
- app/views/oralReport/page8.scala.html
- app/views/shortFormatPreSentenceReport/page4.scala.html
- small content changes following QA
> Oral report content changes

- app/data/OralReportData.java
- app/views/oralReport/hiddenInputs/page7Fields.scala.html
- app/views/oralReport/page7.scala.html
:sparkles: Included 4th static assessment tool option
> PIC-882 Risk assessment changes

- app/data/OralReportData.java
- app/views/oralReport/hiddenInputs/page7Fields.scala.html
:bug: Corrected issue with entered text not being stored
:speech_balloon: Corrected error messages
> PIC-892 Risk of reoffending 

- app/views/oralReport/page7.scala.html
> PIC-891 Risk tool level

- app/views/oralReport/cancelled.scala.html
- app/views/oralReport/completed.scala.html
:bug: Included missing hidden fields on completion and cancel screens
> BUGFIX - Include missing hidden fields on cancel and completion screens

- app/views/paroleParom1Report/page2.scala.html
:speech_balloon: Included the please note content
> PIC-1256 Please note

- app/data/ParoleParom1ReportData.java
- app/views/paroleParom1Report/page23.scala.html
- features/bdd/paroleparom1report/signature.feature
:speech_balloon: Change from LDU to PDU
> PIC-1265 Signature - Change from LDU to PDU

- app/data/ParoleParom1ReportData.java
- app/views/paroleParom1Report/page19.scala.html
- app/views/paroleParom1Report/page20.scala.html
- features/bdd/paroleparom1report/oralHearing.feature
- test/bdd/paroleparom1report/OralHearingSteps.java
:speech_balloon: Changed oral hearing title
> PIC-1263 Member case assessment and oral hearing considerations

- app/data/ParoleParom1ReportData.java
- app/views/paroleParom1Report/hiddenInputs/page21Fields.scala.html
- app/views/paroleParom1Report/page21.scala.html
- features/bdd/paroleparom1report/sources.feature
- test/bdd/paroleparom1report/SourcesSteps.java
:sparkles: Added On/post Tariff Parole Custody Report
> PIC-1264 Sources

- app/data/ParoleParom1ReportData.java
- app/views/paroleParom1Report/hiddenInputs/page19Fields.scala.html
- app/views/paroleParom1Report/page19.scala.html
- features/bdd/paroleparom1report/recommendation.feature
- test/bdd/paroleparom1report/RecommendationSteps.java
:sparkles: Added prison liaison confirmation
> PIC-1262 Prison liaison

- app/data/ParoleParom1ReportData.java
- app/views/paroleParom1Report/hiddenInputs/page15Fields.scala.html
- app/views/paroleParom1Report/hiddenInputs/page16Fields.scala.html
- app/views/paroleParom1Report/hiddenInputs/page17Fields.scala.html
- app/views/paroleParom1Report/page15.scala.html
- app/views/paroleParom1Report/page16.scala.html
- app/views/paroleParom1Report/page17.scala.html
- features/bdd/paroleparom1report/resettlementPlan.feature
- features/bdd/paroleparom1report/riskManagementPlan.feature
- features/bdd/paroleparom1report/supervisionPlan.feature
- test/bdd/paroleparom1report/ResettlementPlanSteps.java
- test/bdd/paroleparom1report/RiskManagementPlanSteps.java
- test/bdd/paroleparom1report/SupervisionPlanSteps.java
:fire: Removed Yes/No questions on pages 15, 16 and 17
> PIC-1347 Remove Yes/No options

- helm_deploy/values-test.yaml
To support Version1 automated tests
> Allow access from Delius test environment
